services:
  front-end:
    build: 
      context: "../front-end"
      args:
        - PORT=8000
    ports:
      - "8080:4200"

  back-end:
    build:
      context: "../back-end"
    ports:
      - "8000:9428"