services:
  back-end:
    build:
      context: "../back-end"
    ports:
      - "8000:9428"
    healthcheck:
      test: curl -f http://localhost:9428/api/status | grep 'ok' || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
  
  front-end:
    build: 
      context: "../front-end"
      args:
        - PORT=8000
    ports:
      - "8080:4200"
    volumes:
      - database:/back-end/database
    healthcheck:
      test: curl -f http://localhost:4200/api/status | grep 'ok' || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      back-end:
        condition: service_healthy

volumes:
  database: