services:
  back-end:
    build:
      context: "../back-end"
    ports:
      - ":9428"
    healthcheck:
      test: curl -f http://localhost:9428/api/status | grep 'ok' || exit 1
      interval: 15s
      timeout: 5s
      retries: 3
  
  front-end:
    build: 
      context: "../front-end"
      args:
        - PORT=4200
    ports:
      - ":4200"
    volumes:
      - database:/back-end/database:rw
    healthcheck:
      test: curl -f http://localhost:4200 || exit 1
      interval: 15s
      timeout: 5s
      retries: 3
    depends_on:
      back-end:
        condition: service_healthy
  
  playwright:
    build:
      dockerfile: "Dockerfile.test"
      context: "../front-end"
    volumes:
      - test-results:/front-end/test-results
    depends_on:
      front-end:
        condition: service_healthy


volumes:
  database:
  test-results: